### PR TITLE
Finally!  Something that is easy and works for all

### PR DESCRIPTION
**Pull request by suresttexas00**
Remove the whole remove.os thing!  It is not needed anymore because wrapper writes a fresh file at each changeover of the logs!  Also removed unneeded (and did not work anyway) sleep() statements.   Removed unneeded f.close() statement in `with` block.  Set timer loop for one minute versus each second... Not a big deal, but why test a day change each second?

### CODE REVIEW

**Comment by benbaptist** [comment]
because a day change could happen at any second...

**Comment by benbaptist** [comment]
Also, I forgot to mention that I manually merged this a while back and to close this. So here goes nothing..

Manually merged.

**Comment by suresttexas00** [comment]
Yes, but that is kind of arbitrary.  The day also changes any NS, MS, second, minute or hour.  The only point is to create a new log every day.  Just seems like every second is overkill.  I have to imagine that  the built in time.sleep uses less overhead than an IF statement that is always checking for something...  But I don't know...

**Comment by benbaptist** [comment]
Yes, but I'd rather have just a one-second leak into the next log than a 1-minute or even longer leak. One second does absolutely zero harm and is not overkill in any possible way. Literally nothing is wrong with it. The amount of CPU being used is so low, that it would still make zero difference on a Commodore 64. That's the level of unimportance that we're talking about right now.

**Comment by suresttexas00** [comment]
I think its just 'cause "YOU IS STUBBORN!" XD... lol

**Comment by benbaptist** [comment]
Nope. I'd rather not have confusion. I can throw the same argument back at you since you're so consistent on 60 seconds instead, when it makes no difference except making it less accurate. :P

**Comment by suresttexas00** [comment]
The difference is I don't care about accuracy and I don't really care what the value is, specifically.  I simply think that when the purpose is just to change a log over once in a while, running this each second is overkill...  that statement was a joke, not an argument ;)

**Pull request closed without merging**
