### PR TITLE
Refactored build script and renamed docs to build

### PR DESCRIPTION
**Pull request by JasonBristol**
Refactored the build script using zipfile and argparse. Script can now be called with arguments can point to a different root directory.

When ran from the `build` directory:
```bash
python build_script.py .. dev -v
```
Renamed the "docs" folder to "build" to correctly emphasize its purpose.

### CODE REVIEW

**Comment by benbaptist** [comment]
Wow, that's fancy! :+1:

**Comment by suresttexas00** [comment]
I wonder why there are conflicts?  Did you create this from the latest dev version?

**Comment by suresttexas00** [comment]
Yes, You used the build 110.. You need the build 111 CHANGELOG.dev.md and Wrapper.py.md5 to resolve the conflicts

**Comment by JasonBristol** [comment]
I did, looks like Ben's latest commit (build 111) naturally modified the
md5 hash file and the build file.

**Comment by JasonBristol** [comment]
Beat me too it ;) was submitted pre build 111, I will resubmit PR to resolve

**Comment by suresttexas00** [comment]
Yes, the md5 hash is updated when you create a new build.. that was done when created the PR for build 111... The only one we need to worry about specifically is the changelog.

**Comment by JasonBristol** [comment]
I will include the change log in my new PR

**Comment by benbaptist** [comment]
It is probably best to have your git ignore Wrapper.py, the hash and all
the other build-related files to reduce confusion

**Comment by suresttexas00** [comment]
I tend to agree.  Build numbers don't need to be incremented constantly as non-API related changes are be being made, and especially where the change does not affect the contents of the /src folder.

**Comment by JasonBristol** [comment]
That is a good point, in the future I think we should write up a spec to
define what changes elicit a build increment vs normal commits

**Comment by benbaptist** [comment]
It doesn't really matter what it is - the build number indicates a new build. A new build needs to be understood for the sake of knowing what's newer and what's older. If you want to discuss whether or not we build every time, that's a different story, but for actual builds, it makes sense to increment every time. :P

But in any case, I decided to start a wiki page for contribution guidelines. Feedback would be awesomesauce!

**Pull request closed without merging**
