### PR TITLE
Create mcperms.py

### PR DESCRIPTION
**Pull request by suresttexas00**
Allow setting permissions for all the vanilla server and Wrapper commands.  This allows you to set a player as OP, yet still limit his commands to those you allow... because vanilla OP levels 1-4 are useless in real life!
This plugin actually does not function 'stand-alone'. it is meant to simply be referenced by an existing plugin that may already be using a player.rawMessage event..

If no other plugin has registered player.rawMessage, a simple plugin to run this would be:
```
NAME = "perms"
AUTHOR = "SurestTexas00"
ID = "com.suresttexas00.plugins.perms"
VERSION = (0, 1)
SUMMARY = "provide permissions for vanilla commands"
WEBSITE = ""
DESCRIPTION = "provide permissions for vanilla commands"
DEPENDENCIES = ["mcperms.py"]

class Main:
    def __init__(self, api, log):
        self.api = api
        self.log = log
        self.minecraft_permission = api.getPluginContext("com.suresttexas00.plugins.mcperms")

    def onEnable(self):
        self.api.registerEvent("player.rawMessage", self.playerRawMessage)

    def onDisable(self):
        pass

    def playerRawMessage(self, payload):
        player = payload["player"]
        messageargs = (payload["message"]).split(" ")
        if self.minecraft_permission.playerRawMessage_hook_mcperms(player, messageargs) is False:
            return False

```

### CODE REVIEW

**Comment by JasonBristol** [comment]
+1, certainly a value add for Wrapper.py since the OP 1-4 really is not granular enough

**Comment by suresttexas00** [comment]
Do you think the code snippet included above should be included as a separate plugin to run it?

**Comment by JasonBristol** [comment]
I think tactically using the above snippet as a plugin works fine, ideally I could see mcperms being merged into the API itself (`__init.py__`?) -- capturing both wrapper commands and vanilla commands in the same breath. This would allow for a centralized interface for managing both and might also have some performance benefits.

**Comment by suresttexas00** [comment]
Meant to delete patch-1

**Comment by suresttexas00** [comment]
I'll move this to the uberdev branch.

**Pull request closed without merging**
