### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Darkness3840**
Added readline and pyreadline to dependencies.

### CODE REVIEW

**Comment by suresttexas00** [comment]
I really think your situation is unique.  Most distros and their pythons already have readline installed.  I addressed readline [here](https://github.com/benbaptist/minecraft-wrapper/commit/c98660743225bf70e212c63eb830e066bd41baf2#diff-04c6e90faac2675aa89e2176d2eec7d8).

what is pyreadline in the import?

**Comment by Darkness3840** [comment]
Installing pyreadline fixed the command history for me. Arrow up and down

**Comment by suresttexas00** [comment]
where is the code for its import?

**Comment by Darkness3840** [comment]
I believe it's just an extension to readline

**Comment by suresttexas00** [comment]
As far as I know, just installing a module on your system using pip does not do anything unless the code you are running imports it somewhere.  Wrapper imports readline in line 34 of ./core/wrapper.py.  unless readline attempts to import pyreadline, then pyreadline is doing nothing (unless you modded the code to install is somewhere).

If pyreadline is "overriding" readline as the readline import (the only other possiblity), then readline is the unneeded module.  You could test for that by removing (using PIP) the readline from you system and then seeing if everything still works right.  If pyreadline is better, we may want to use it.

**Comment by suresttexas00** [comment]
I just mentioned that because i know pyCrypto and pyCryptodome import identically as "Crypto"...

**Comment by suresttexas00** [comment]
My quick look on google just shows it as a module for windows readline (may be helpful for windows) and for iron python.  See if your arrow keys still work without it under build 126.

**Comment by suresttexas00** [comment]
I have had a few different Linux's (and windows 8.1 originally when I started my first servers) with wrapper and never had to install readline with any of them.  I inserted that yellow checker warning log item because I was curious if someone, at some point would not have readline (I figured it would end up being a windows user though!!).

**Comment by suresttexas00** [comment]
Too bad I don't have windows computers any longer to test how wrapper behaves now.

**Comment by Darkness3840** [comment]
I think it's safe to say that most people using wrapper will be using it on linux systems.

**Comment by suresttexas00** [comment]
There are a number of Windows users...

**Comment by suresttexas00** [comment]
Were you able to verify your up/down arrows and history still work with the pyreadline removed?

**Comment by Darkness3840** [comment]
Oh, sorry, I forgot to get around to that. I will let you know once I do.

**Comment by Darkness3840** [comment]
The arrow keys do work without pyreadline.

**Pull request closed without merging**
