### PR TITLE
Add server-directory configuration option

### PR DESCRIPTION
**Pull request by Cougar**
Having server-directory different than "." makes it possible to keep
Minecraft server files in separate directory

I'm not 100% satisfied with this patch because it uses self.wrapper.config["General"]["server-directory"]) in too many places but this helps a lot to keep the Wrapper directory clean and makes it much simpler to work with Wrapper without touching server files.

### CODE REVIEW

**Comment by suresttexas00** [comment]
I dont know alot about GIT and so forth, but shouldn't these patches be made into the dev version first?

**Comment by Cougar** [comment]
Hmm.. This depends on how we (or You) develop the code ;-)

I basically agree that new features should first go to dev branch and only bugfixes go directly to the master branch. I depends. In some cased dev is all time broken code that can't be much used and in some cases dev is quite good in quality and almost as usable as master branch.

I can pull this to the dev as well. No problem ;-)

Is there doc, issue or other place where such rules are written? I mean things like how often dev is merged with master and so on?

**Comment by suresttexas00** [comment]
Well, I think the way this has generally worked is that when the dev code seems to be a good working version, it is pushed to the Master ("stable"?).  The new changes are generally made in the dev code.. unless it is a real bad bug that needs an emergency fix.

**Comment by suresttexas00** [comment]
I suppose may be it would be better to call these not "master" and "dev", but "stable" and "dev"...

**Comment by suresttexas00** [comment]
"stable" meaning not that it is necessarily free of bugs, but that it is not changing frequently.  Dev normally contains the latest bug fixes and newer features.

**Comment by Cougar** [comment]
I made a new pull request #171 against development branch. This one can be closed.

**Pull request closed without merging**
