### PR TITLE
Make group info list more user friendly

### PR DESCRIPTION
**Pull request by suresttexas00**
Displaying the human lastname with the UUID to make it easier to know who is in a group.

### CODE REVIEW

**Comment by suresttexas00** [comment]
image
 versus:
image

**Comment by benbaptist** [comment]
Fixed in #97.

**Comment by suresttexas00** [comment]
`Implemented/merged manually in #97.`
you should user No.97 ... or similar, otherwise github thinks you are referring to #97

**Comment by benbaptist** [comment]
heh yeah, I always forget to do that.

**Pull request closed without merging**
