### PR TITLE
Add player.createsign event (signedit 0x12 packet)

### PR DESCRIPTION
**Pull request by suresttexas00**
Parse 0x12 signedit from Client to server.  Add player.createsign event that can be returned False (resulting in a blank sign) or the payload can be modified and returned.  Lines are "chat" objects and should be single quoted outside and double quoted inside for text items.
Sample plugin Code:
```
    def onEnable(self):
        self.api.registerEvent("player.createsign", self._createsign)

    def _createsign(self, payload):
        line1 = payload["line1"]
        if "Something Bad" in line1:
            payload["line1"] = '"Forget about it!"'
            payload["line2"] = '""'
            payload["line3"] = '""'
            payload["line4"] = '""'
            return payload
        print payload
```

My suggested use for this is to have a plugin limit the length of the chat objects (hacked clients out there doing server crashes with signs) or let players create json in signs (colored, linked, etc)

### CODE REVIEW

**Comment by suresttexas00** [comment]
I don't believe the lines are truly Chat objects despite what the protocol docs say.   I also note that the 1.9 protocol doc has changed them to "string" types.

**Comment by benbaptist** [comment]
Manually merged into build 107.

**Comment by benbaptist** [comment]
One word of warning about this: you can't trust everything the client sends, and in this case, we need to eventually make sure that the player actually placed a sign down so that we know the player.createsign is actually valid and the player just created a new sign. That doesn't need to be implemented for now, but later on, it will be needed.

**Comment by suresttexas00** [comment]
Very true... shady clients :P   It suits my purposes though because my server can log/record sign activity and who wrote the sign (or attempted to).

**Comment by benbaptist** [comment]
Indeed. Later down the road, I'd like to start securing certain inputs from the client, and verifying them a bit more. But it'll require a bit more info to be parsed from the server side (i.e. reading chunk data, etc.) before we get there.

**Pull request closed without merging**
