### PR TITLE
Add server-directory configuration option

### PR DESCRIPTION
**Pull request by Cougar**
Pull request  #170 against development branch.

### CODE REVIEW

**Comment by benbaptist** [comment]
Would it be better just to change the directory of the whole Wrapper script? It appears this just changes everything manually - I'm not sure if this is the best way to do it or not. 

os.chdir() would probably have the same effect

**Comment by Cougar** [comment]
os.chdir() doesn't do what I'd like. I'd like to keep all wrapper files in wrapper directory. This gives much better playground and makes is easier to work with backups if you always know what files belong to Minecraft server and what belong to wrapper.

Right now only exception is plugin JSON data which will be written in the Minecraft world/plugins directory. I would actually like to move them also out to the wrapper directory to keep Vanilla server as standard as possible and mess around outside it ;-)

As I said I also don't like this patch because of so big number of long lines. This just does not like nice but it works. Would be much better to have some wrapping of these parameters or even special methods to get filenames for example..

**Comment by suresttexas00** [comment]
I agree, the plugins data should come out of the world directory and have it's home in the wrapper directory

**Comment by suresttexas00** [comment]
I like the idea of having the wrapper script OUT of the server directory with a config option to tell wrapper where minecraft is;
As far as the plugins folder, I like what bukkit does and places the plugins folder in the minecraft folder (but not in the world folder).

**Comment by benbaptist** [comment]
I'm going to try to merge this soon - I'll probably change a few things, but it should work.

**Comment by suresttexas00** [comment]
I think this should work.. the only change I would make is to replace all the `self.config["General"]["server-directory"]` items with a `self.wrapper.serverFolder` item that is just read in upon wrapper (or server?) restarts.

Just one little aside; @Cougar (not sure if you still follow or are active with wrapper), you can draw the plugin json data out of the minecraft world folder using 'False' in getStorage():

`self.playerdata = self.api.getStorage("playerdata", `__False__`)`

**Comment by suresttexas00** [comment]
No activity for some time on this.  re-opened as https://github.com/suresttexas00/minecraft-wrapper/issues/78

**Pull request closed without merging**
